spring:
  application:
    name: karaplan
  data:
    redis:
      repositories:
        enabled: false
    rest:
      detection-strategy: annotated
  jackson:
    default-property-inclusion: non-empty
  jpa:
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate.globally_quoted_identifiers: true
  main:
    lazy-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: toComplete
            client-secret: toComplete
          github:
            client-id: toComplete
            client-secret: toComplete
            scope: read:user,user:email
          facebook:
            client-id: toComplete
            client-secret: toComplete
  session:
    store-type: none
    redis:
      namespace: karaplan:session
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 30d
server:
  port: 8080
  compression:
    enabled: true
  error:
    include-message: always
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 12h
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: [health, info]
  endpoint:
    health:
      probes:
        enabled: true
  health:
    redis:
      enabled: false
karaplan:
  karafun:
    remote:
      endpoint: https://www.karafun.com
      endpoint-for-locale:
        de: https://www.karafun.de
        en: https://www.karafun.com
        es: https://www.karafun.es
        fr: https://www.karafun.fr
        it: https://www.karafun.it
        nl: https://www.karafun.nl
    web:
      endpoint: https://www.karafun.com
      endpoint-for-locale:
        de: https://www.karafun.de
        en: https://www.karafun.com
        es: https://www.karafun.es
        fr: https://www.karafun.fr
        it: https://www.karafun.it
        nl: https://www.karafun.nl
  kv:
    endpoint: https://www.karaoke-version.com/api
    endpoint-for-locale:
      de: https://www.karaoke-version.de/api
      en: https://www.karaoke-version.com/api
      es: https://www.version-karaoke.es/api
      fr: https://www.version-karaoke.fr/api
      it: https://www.versione-karaoke.it/api
      nl: https://www.karaoke-versie.nl/api
