runtime: java11
instance_class: F4
entrypoint: java -jar karaplan.war
handlers:
  - url: /(.*\.(js|css|png|jpg|svg|ico|xml|webmanifest))$
    static_files: WEB-INF/classes/static/\1
    upload: WEB-INF/classes/static/.*\.(js|css|png|jpg|svg|ico|xml|webmanifest)$
  - url: /.*
    secure: always
    script: auto
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1024m -Xms512m -Xmx512m"
  SPRING_PROFILES_ACTIVE: "gcp,appengine"
automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: 5000ms
  max_concurrent_requests: 50
  target_throughput_utilization: 0.9
  target_cpu_utilization: 0.9
inbound_services:
  - warmup
# Uncomment and configure the following block to allow access to VPC resources such as Memorystore (Redis)
# See: https://cloud.google.com/vpc/docs/configure-serverless-vpc-access
#vpc_access_connector:
#  name: "projects/<project-id>/locations/<region>/connectors/<connector>"
